import puppeteer from 'puppeteer-core'
const B='http://localhost:3300'
const br = await puppeteer.launch({ executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new' })
const p = await br.newPage()
const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,120)))
await p.goto(B,{waitUntil:'networkidle2'})
await p.evaluate(()=>localStorage.setItem('ascent-v1', JSON.stringify({state:{level:'boom',answers:{advisor:{top3:['x','y','z'],dependence:'NaN'},route:{years:['nope',null,[{}]]},fuel:'no',trials:{evil:{answer:'maybe'}},capacity:{spend:{evil:999}}}},version:1})))
await p.goto(B,{waitUntil:'networkidle2'}); await new Promise(r=>setTimeout(r,900))
console.log('after hydrate, h1:', await p.evaluate(()=>document.querySelector('h1')?.textContent?.slice(0,40)))
console.log('pageerrors:', errs.length ? errs[0] : 'none')
// force a state write so the persisted blob is rewritten from in-memory state
await p.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='USPB'); b?.click()})
await new Promise(r=>setTimeout(r,400))
const st = await p.evaluate(()=>JSON.parse(localStorage.getItem('ascent-v1')).state)
console.log('IN-MEMORY (rewritten) ->')
console.log('  level:      ', JSON.stringify(st.level))
console.log('  top3:       ', JSON.stringify(st.answers.advisor.top3))
console.log('  dependence: ', JSON.stringify(st.answers.advisor.dependence))
console.log('  trials:     ', JSON.stringify(st.answers.trials))
console.log('  spend:      ', JSON.stringify(st.answers.capacity.spend))
console.log('  route.years:', JSON.stringify(st.answers.route.years))
console.log('  fuel:       ', JSON.stringify(st.answers.fuel))
await br.close()
