import puppeteer from 'puppeteer-core'
const br = await puppeteer.launch({ executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new' })
const p = await br.newPage(); await p.setViewport({width:1280,height:900,deviceScaleFactor:2})
await p.goto('http://localhost:3000',{waitUntil:'networkidle2'}); await p.evaluate(()=>localStorage.clear())
await p.goto('http://localhost:3000',{waitUntil:'networkidle2'}); await new Promise(r=>setTimeout(r,1800))
await p.evaluate(()=>{[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Begin the climb'))?.click()})
await new Promise(r=>setTimeout(r,900))
await p.screenshot({path:'.context/shots/l0-assoc.png'})
console.log(await p.evaluate(()=>document.querySelector('h1').textContent))
console.log(await p.evaluate(()=>[...document.querySelectorAll('.glass > div > div > div')].map(d=>d.textContent?.slice(0,46)).filter(Boolean).slice(0,6)))
await br.close()
