import puppeteer from 'puppeteer-core'
const br = await puppeteer.launch({ executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless:'new' })
const p = await br.newPage(); await p.setViewport({width:430,height:760,deviceScaleFactor:2,isMobile:true,hasTouch:true})
await p.goto('http://localhost:3000',{waitUntil:'networkidle2'})
await p.evaluate(()=>localStorage.setItem('ascent-flow-v1', JSON.stringify({state:{started:true,path:['hello','prep'],answers:{}},version:1})))
await p.goto('http://localhost:3000',{waitUntil:'networkidle2'}); await new Promise(r=>setTimeout(r,900))
const before = await p.evaluate(()=>({flag: !!document.querySelector('svg path[d^="M0 -24"]'), next: [...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Next')?.disabled}))
await p.screenshot({path:'.context/shots/scale-untouched.png'})
await p.evaluate(()=>[...document.querySelectorAll('[role=radio]')].find(b=>b.textContent.includes('Mostly ready'))?.click())
await new Promise(r=>setTimeout(r,300))
const after = await p.evaluate(()=>({flag: !!document.querySelector('svg path[d^="M0 -24"]'), next: [...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Next')?.disabled, readout: document.querySelector('[aria-live=polite]')?.textContent}))
await p.screenshot({path:'.context/shots/scale-tapped.png'})
console.log('untouched: flag drawn =', before.flag, '| Next disabled =', before.next)
console.log('tapped:    flag drawn =', after.flag, '| Next disabled =', after.next, '| reads', JSON.stringify(after.readout))
await br.close()
