/* Build src/game/art/sprites.ts from the 3D renders in public/game/3d.
   Run after copying new renders:  node scripts/sprites.mjs
   A render named <id>.webp replaces the drawing for <id>; <id>-<state>.webp
   replaces it for that state (rucksack-zipped, fu-door-ajar ...).
   A sharper copy at twice the size may sit in public/game/3d/2x/<key>.webp
   (the same framing and aspect): the desk layout draws it, the phone keeps
   the 1x file (Art in art/index.tsx). SPRITES then lists the 2x size, the
   render's true natural size; SPRITES_2X lists the keys that have one. */
import fs from 'node:fs'
import path from 'node:path'

const DIR = 'public/game/3d'
// Pieces whose geometry the game logic depends on stay drawn: slider tracks,
// the stacked cairn, the brick plate and anything procedural.
const KEEP_DRAWN = new Set([
  'track-switchback', 'track-ridge', 'bootprints', 'cairn-stone', 'baseplate', 'crate',
  'route-layers', 'snow-overlay', 'strap-kit',
  // the rope's three clips are drop targets positioned on the drawing
  'rope-clips',
])

function webpSize(file) {
  const b = fs.readFileSync(file)
  const chunk = b.subarray(12, 16).toString('latin1')
  if (chunk === 'VP8X') return [b.readUIntLE(24, 3) + 1, b.readUIntLE(27, 3) + 1]
  if (chunk === 'VP8 ') return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff]
  if (chunk === 'VP8L') { const v = b.readUInt32LE(21); return [(v & 0x3fff) + 1, ((v >> 14) & 0x3fff) + 1] }
  throw new Error(`not a webp: ${file}`)
}

const rows = fs.readdirSync(DIR).filter((f) => f.endsWith('.webp')).sort()
  .map((f) => [path.basename(f, '.webp'), webpSize(path.join(DIR, f))])
  .filter(([key]) => ![...KEEP_DRAWN].some((id) => key === id || key.startsWith(id + '-')))

// the 2x copies: listed at their own (larger) size
const HI = path.join(DIR, '2x')
const hi = new Set()
for (const row of rows) {
  const f = path.join(HI, `${row[0]}.webp`)
  if (!fs.existsSync(f)) continue
  const [w, h] = webpSize(f), [w1, h1] = row[1]
  if (Math.abs(w - 2 * w1) > 2 || Math.abs(h - 2 * h1) > 2) throw new Error(`${f} is ${w}x${h}, not twice ${w1}x${h1}`)
  row[1] = [w, h]
  hi.add(row[0])
}

const body = rows.map(([k, [w, h]]) => `  '${k}': [${w}, ${h}],`).join('\n')
fs.writeFileSync('src/game/art/sprites.ts', `/* Generated by scripts/sprites.mjs from public/game/3d. Do not edit by hand.
   key -> [width, height] of the 3D render. */
export const SPRITES: Record<string, readonly [number, number]> = {
${body}
}

/** Keys with a 2x copy in public/game/3d/2x (drawn on desk). */
export const SPRITES_2X: ReadonlySet<string> = new Set([
${[...hi].sort().map((k) => `  '${k}',`).join('\n')}
])
`)
console.log(`${rows.length} sprites, ${hi.size} with a 2x copy`)
